### ISSUE TITLE
More ways to load the webpack config

### ISSUE THREAD

**Issue by zvictor** [SectorLabs/babel-plugin-transform-named-imports#8]
First, thanks for the great concept and good work done so far!  🎉

**Problem**

I am using nextjs in my application, which doesn't let me have a webpack configuration stored as a simple `./webpack.config.js`. Instead, it let me expand its default webpack settings by defining a `webpack` key in the exported object of the file `next.config.js`. The final webpack config is generated in runtime by nextjs itself.

**Questions**

* What others ways could I define the webpack config in  babel-plugin-transform-named-imports?
* Would you have any idea of how we could make tools like nextjs work well with it?

**Comment by zvictor** [comment]
I forgot to mention, but nextjs has a utility to generate the webpack config that we probably want to run somewhere and pass the results down in babel-plugin-transform-named-imports:

```js
const webpackConfig = require('next/build/webpack').default() //async
```

source: [next/build/webpack:118](https://github.com/zeit/next.js/blob/10a9178e3206270fd6e317df2e0a4dbffb460a6e/build/webpack.js#L118)

**Comment by Photonios** [comment]
Would it help to have an option in this plugin that allows invoking an arbitrary JS file with a function in it that returns a Webpack configuration? This would allow you to generate the Webpack config and then give it back to the plugin. I imagine something like this:

```
// generate-webpack-config.js
const webpackConfig = require('next/build/webpack').default();
module.exports = webpackConfig;

// in .babelrc
["transform-named-imports", {
      "generateWebpackConfig": "./generate-webpack-config.js"
}]
```

**Comment by JHawkley** [comment]
@Photonios Its important to be clear that the result of `require('next/build/webpack').default()` would be a promise, in this case.  So, to get Next.js support, you would need to `await` on the Webpack configuration.  Unfortunately, I don't think Babel plugins supports asynchronous initialization at this time.  [It's on their roadmap](https://babeljs.io/docs/en/roadmap#async-transforms), though.

Hmm...  I wonder if there's any other way to get this to work.  I would really love to be able to use this plugin.

Since you're using `eslint-import-resolver-webpack` to handle module resolution on your behalf, this module supports providing an explicit config object, and that config object really only needs a handful of properties.  Might it be possible to simply provide such an object to `transform-named-imports` instead of a path?

Then, in Next.js, we could inject the plugin into the `defaultLoaders.babel` object that Next.js provides in its Webpack configuration method:

```javascript
// next.config.js

module.exports = {
  webpack(config, { defaultLoaders } }) {
    const babelPlugins = defaultLoaders.babel.options.plugins || [];
    
    babelPlugins.push([
      "transform-named-imports", {
        // Provide an object instead of a string.
        "webpackConfig": {
          // These are the only three properties
          // considered by `eslint-import-resolver-webpack`.
          "resolve": config.resolve,
          "plugins": config.plugins,
          "externals": config.externals
        }
      }
    ]);
    
    defaultLoaders.babel.options.plugins = babelPlugins;
    
    return config;
  }
}
```

I _think_ this would work...?

This would pretty much only require adding a quick `typeof` check in the `Resolver` class to determine if it should load from a path or just pass along the object to `eslint-import-resolver-webpack`.

**Comment by eirikurn** [comment]
I have the same problem. My resolve rules are quite simple so I'd be happy to pass in a minimal webpack config as an object.

**Comment by JHawkley** [comment]
I've been working on turning this Babel plugin into [a proper Webpack 4 loader](https://github.com/JHawkley/resolve-imports-loader).  It has consideration for side-effects and inter-operates with other Webpack loaders correctly, including loaders that transform non-javascript files (which was one of the problems I was having with this plugin).  It is in an operational state and has been behaving well with my current 400+ module code-base.

I have not yet published it to NPM (I'm still trialing it and working on increasing test coverage), so if you want to give it a go, you'll need to add it to your `package.json` as [a Git dependency](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies) for the time being.

**Comment by Photonios** [comment]
My apologies for the long delay. I've pushed a commit that adds support for passing a Webpack config object: https://github.com/SectorLabs/babel-plugin-transform-named-imports/commit/dc471cba5161a7d5d28021b1b22126989228a5de

If you're still interested, please give it a shot :)
